Models/Author.cs
public class Author
{

    public Author()
    {
        List<Book> Books = new List<Book>();
    }

    public int AuthorId { get; set; }
    public string AuthorName { get; set; } = string.Empty;

    public IList<Book> Books { get; set; }
}

Models/Book.cs
public class Book
{
    public int BookId { get; set; }
    public string Title { get; set; } = string.Empty;
    public int Copies { get; set; }

    public int AuthorId { get; set; }
    public Author Author { get; set; }
}

Models/ErrorViewModel.cs
namespace Bookish.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/CatalogueController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Bookish.Models;
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.EntityFrameworkCore;

namespace Bookish.Controllers;

public class CatalogueController : Controller
{

    private readonly BookishDbContext _context;

    public CatalogueController(BookishDbContext context)
    {
        _context = context;
    }

    // GET: /Catalogue/
    //same as GET: /Catalogue/BookList/
    public async Task<IActionResult> BookList()
    {
        var books = await _context.Books
            .Include(x=>x.Author)
            .ToListAsync();

        return View(books);
    }

    // GET: /Catalogue/BookDetails/{id}?book=title/ 
    public async Task<IActionResult> BookDetails(int? id = 1)
    {

        var book = _context.Books
            .Include(x=>x.Author)
            .FirstOrDefault(b => b.BookId == id);

        if (book == null)
        {
            return NotFound();
        }

        return View(book);
    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Bookish.Models;

namespace Bookish.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Catalogue/BookDetails.cshtml
@model Book

@{
    ViewData["Title"] = "Book Details";
}

<div class="text-center">
    <h1 class="display-4">Book Details</h1>
</div>

@* <ul>
    <li>@Model.Title (@Model.AuthorId)</li>
</ul> *@

<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Copies)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Copies)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author.AuthorName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.AuthorName)
        </dd>
    </dl>
</div>

Views/Catalogue/BookList.cshtml
@model IEnumerable<Book>

@{
    ViewData["Title"] = "Book List";
}

<div class="text-center">
    <h1 class="display-4">Our Book Catalogue</h1>
</div>

@* @foreach (var book in Model) {
    <p>Title: @book.Title, Author: @book.AuthorId, Available copies: @book.Copies</p>
} *@

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author.AuthorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Copies)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author.AuthorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Copies)
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookish</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bookish.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookish</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalogue" asp-action="BookList">Catalogue</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Bookish - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>